"""Shared fixtures for aionepviewer tests."""

from __future__ import annotations

import pytest

SIGN_IN_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "userInfo": {
            "uid": "test_uid",
            "email": "test@example.com",
            "country": "US",
            "state": "California",
            "role": 0,
            "groupId": 26,
            "groupName": "End User",
            "headerImg": "",
            "fullHeaderImg": "",
            "defaultArea": "NA",
            "companyId": 0,
            "isCompanyOwner": 0,
            "oemid": 0,
            "oemweb": "NEP",
        },
        "tokenInfo": {
            "token": "fake.jwt.token",
            "expiresAt": 9999999999,
            "duration": 43200,
        },
        "siteCount": 1,
    },
}

DEVICE_LIST_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "list": [
            {
                "sid": "US_TEST_SITE",
                "sn": "AABB1122",
                "status": 0,
                "statusTitle": "online",
                "alertCode": "0000",
                "alertTitle": "OK",
                "alertDescription": "ok",
                "model": 11,
                "modelName": "BDM-2250",
                "lastUpdateTime": 1700000000,
                "lastUpdate": "01/01/2026 12:00",
                "lastUpdateCal": "Just now",
                "createdAt": "01/01/2026 00:00",
                "siteName": "Test Site",
                "country": "US",
                "countryName": "United States",
                "stateName": "California",
                "city": "Los Angeles",
                "street": "123 Solar St",
                "userEmail": "test@example.com",
                "installerEmail": "installer@example.com",
                "commissionDate": "01/01/2026 00:00",
                "now": 1500,
                "nowUnit": "W",
                "batterySoc": 0,
                "WIFIVersion": "3.01.25",
                "CPUVersion": "",
                "RAMVersion": "",
                "alias": "",
            },
        ],
        "total": 1,
    },
}

SITE_LIST_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "list": [
            {
                "sid": "US_TEST_SITE",
                "siteName": "Test Site",
                "country": "US",
                "countryName": "United States",
                "stateName": "California",
                "city": "Los Angeles",
                "street": "123 Solar St",
                "userEmail": "test@example.com",
                "installerEmail": "installer@example.com",
                "registerDate": "01/01/2026 00:00",
                "isCommission": False,
                "commissionDate": "",
                "snCount": 1,
                "sn": [
                    {
                        "sid": "US_TEST_SITE",
                        "sn": "AABB1122",
                        "model": "BDM-2250",
                        "status": 0,
                        "statusTitle": "online",
                        "alertCode": "0000",
                        "alertTitle": "OK",
                        "alertDescription": "ok",
                        "lastUpdate": "01/01/2026 12:00",
                        "lastUpdateCal": "Just now",
                        "lastUpdateTime": 1700000000,
                        "now": 1500,
                        "todayPower": 5.5,
                        "totalPower": 200,
                        "nowUnit": "W",
                        "todayPowerUnit": "kWh",
                        "totalPowerUnit": "kWh",
                    },
                ],
                "status": 0,
                "statusTitle": "online",
                "logo": "",
                "now": 1500,
                "todayPower": 5.5,
                "totalPower": 200,
                "nowUnit": "W",
                "todayPowerUnit": "kWh",
                "totalPowerUnit": "kWh",
                "lastUpdate": "01/01/2026 12:00",
                "lastUpdateCal": "Just now",
                "lastUpdateTime": 1700000000,
            },
        ],
        "total": 1,
    },
}

SITE_OVERVIEW_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "statisticsProduction": {
            "today": "5.5",
            "todayUnit": "kWh",
            "yesterday": "8.2",
            "yesterdayUnit": "kWh",
            "month": "150",
            "monthUnit": "kWh",
            "year": "200",
            "yearUnit": "kWh",
            "total": "200",
            "totalUnit": "kWh",
            "totalNow": "1500",
            "totalNowUnit": "W",
            "totalMoney": "100",
            "todayMoney": "2.5",
            "yesterdayMoney": "3.7",
            "monthMoney": "67.5",
            "totalMoneyUnit": "USD",
        },
        "benefit": {
            "co2": "200",
            "co2Unit": "kg",
            "tree": "9",
            "treeUnit": "Trees",
            "car": "700",
            "carUnit": "km",
            "light": "3333",
            "lightUnit": "H",
            "oil": "0.5",
            "oilUnit": "BBL",
        },
        "status": 0,
        "statusTitle": "online",
        "lastUpdateCal": "Just now",
        "lastUpdate": "01/01/2026 12:00",
        "createdAt": "01/01/2026 00:00",
        "deviceList": [
            {
                "sid": "US_TEST_SITE",
                "sn": "AABB1122",
                "model": 11,
                "modelName": "BDM-2250",
                "status": 0,
                "statusTitle": "online",
                "pageType": 2,
                "now": "1500",
                "today": "5.5",
                "nowUnit": "W",
                "todayUnit": "kWh",
            },
        ],
        "energy": {
            "PVPanel": {
                "power": 1500,
                "powerUnit": "W",
                "direction": 1,
                "show": True,
                "rate": 0,
                "showPower": True,
            },
            "home": {
                "power": 1500,
                "powerUnit": "W",
                "direction": 2,
                "show": True,
                "rate": 0,
                "showPower": False,
            },
            "grid": {
                "power": 1500,
                "powerUnit": "W",
                "direction": 1,
                "show": True,
                "rate": 0,
                "showPower": False,
            },
            "battery": {
                "power": 0,
                "powerUnit": "W",
                "direction": 0,
                "show": False,
                "rate": 0,
                "showPower": False,
            },
            "gen": {
                "power": 0,
                "powerUnit": "W",
                "direction": 0,
                "show": False,
                "rate": 0,
                "showPower": False,
            },
        },
        "alert": {"code": "0000", "title": "OK", "desc": "ok"},
        "max_power": 2000,
        "components": ["device:overview"],
    },
}

MODULES_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "list": [
            {
                "sn": "AABB1122",
                "isPhase": False,
                "modules": [
                    {
                        "plcSN": "AABB1122_1",
                        "addr": 1,
                        "lastUpdate": "2026-01-01 12:00:00",
                        "lastUpdateTime": 1700000000,
                        "now": 400,
                        "todayPower": 1.5,
                        "totalPower": 50,
                        "nowUnit": "W",
                        "todayPowerUnit": "kWh",
                        "totalPowerUnit": "kWh",
                        "version": "",
                        "status": "0000",
                        "page": 0,
                        "model": 0,
                        "model_name": "-",
                    },
                ],
                "status": 0,
                "statusTitle": "online",
                "alertCode": "0000",
                "alertTitle": "OK",
                "model": 11,
                "modelName": "BDM-2250",
                "lastUpdate": "2026-01-01 12:00:00",
                "version": "e606",
                "alias": "",
            },
        ],
        "total_plc": 1,
        "is_all": True,
    },
}

PRODUCT_INFO_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "list": [
            {
                "sn": "86D4EC90",
                "model": 11,
                "modelName": "BDM-2250",
                "funcList": [
                    {
                        "func_id": 5,
                        "func_name": "Parameter Settings",
                        "signal_mqtt": False,
                        "signal_bluetooth": False,
                        "signal_at": False,
                        "signal_ap": True,
                    },
                    {
                        "func_id": 7,
                        "func_name": "800~2000W Power Switch",
                        "signal_mqtt": False,
                        "signal_bluetooth": False,
                        "signal_at": True,
                        "signal_ap": False,
                    },
                    {
                        "func_id": 1,
                        "func_name": "Network Config",
                        "signal_mqtt": False,
                        "signal_bluetooth": False,
                        "signal_at": False,
                        "signal_ap": True,
                    },
                ],
                "is_exist": False,
            },
        ],
    },
}

DEVICE_WIFI_OTA_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": [
        {
            "sn": "86d33ec0",
            "wifiVersion": "3.01.25",
            "advice": 2,
            "address": "",
        },
    ],
}

SITE_LAYOUT_RESPONSE = {
    "code": 200,
    "msg": "Success",
    "data": {
        "sid": "BR_20260317_tXFI",
        "siteName": "Test Site",
        "layoutPic": "",
        "layoutScale": 0,
    },
}